### ISSUE TITLE
Missing concurrency

### ISSUE THREAD

**Issue by troykelly** [troykelly/emby-dedupe#9]
```yaml
# Ensures that only the latest edge workflow is running
concurrency:
  group: edge-workflow
  cancel-in-progress: true
```
